			AREA NUMZEROESONES,CODE,READONLY
NUMONES		RN	1
NUMZEROES	RN	2
NUMBER		RN	3
ENTRY
			MOV R5,#0x40000000
			MOV NUMBER,#0xF
			MOV NUMONES,#0
			MOV NUMZEROES,#0
LOOP
			LSRS NUMBER,#1;LSR BASICALLY DIVIDES THE NUMBER BY 2 IN BINARY AND THE LAST BIT GOES TO STATUS FLAG S
			ADDCS NUMONES,#1;remember it as for NUMONES,USE ADDCS
			ADDCC NUMZEROES,#1;FOR NUMZEROES ADDCC
			CMP NUMBER,#0
			BNE LOOP
			STR NUMONES,[R5],#4
			STR NUMZEROES,[R5]
STOP		B	STOP
			END