			AREA SUMOFODIGITS,CODE
SUM			RN	1
DIGIT		RN	2
QUO			RN	3
DIVISOR		RN	4
N			RN	5
			LDR N,=123
			MOV SUM,#0
			MOV DIVISOR,#10
SUM_OF
			BL LAST_DIGIT
			ADD SUM,DIGIT,SUM
			MOV N,QUO
			CMP QUO,#0
			BNE SUM_OF
GO			BAL	GO
LAST_DIGIT
			MOV QUO,#0
			MOV DIGIT,#0
SUBS_AGAIN
			SUBS N,N,DIVISOR
			ADDPL QUO,QUO,#1
			BPL SUBS_AGAIN
			ADDMI DIGIT,N,DIVISOR
			BX LR
			END